furni/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from furni.views import index, about, shop, thanks,  services, cart, blog, IndexView, ReserveView

from furni_webproject import settings

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('shop/', shop, name='shop'),
    path('services/', services, name='services'),
    path('contact/', IndexView.as_view(), name='contact'),
    path('cart/', cart, name='cart'),
    path('blog/', blog, name='blog'),
    path('checkout/', ReserveView.as_view(), name='checkout'),
    path('successful_order/', thanks, name='successful_order'),

]

furni_webproject/urls.py
# furni_webproject/urls.py

from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from account1.views import RegisterViewUser, LoginViewUser, logout_view
from furni_webproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('furni.urls')),
    path('about/', include('furni.urls', namespace='about')),
    path('shop/', include('furni.urls', namespace='shop')),
    path('services/', include('furni.urls', namespace='services')),
    path('contact/', include('furni.urls', namespace='contact')),
    path('cart/', include('furni.urls', namespace='cart')),
    path('checkout/', include('furni.urls', namespace='checkout')),
    path('successful_order/', include('furni.urls', namespace='successful_order')),
    path('register/', RegisterViewUser.as_view(), name='register'),
    path('login/', LoginViewUser.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('manager/', include('manager.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/urls.py
from django.urls import path, include
from .views import IndexOrderView, IndexView

app_name = 'manager'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('approve/<int:pk>/', IndexOrderView.as_view(), name='approve')
]

manager/models.py
from django.db import models

# Create your models here.

manager/forms.py
from django import forms
from furni.models import Checkout


class OrderForm(forms.ModelForm):
    """
    Form for Order model
    """
    class Meta:
        model = Checkout
        fields = ('first_name', 'last_name', 'country', 'company_name', 'address'
                  , 'postal_code', 'email', 'phone', 'message', 'is_approved')


class EditOrderForm(forms.ModelForm):
    """
    Form for editing
    """
    class Meta:
        model = Checkout
        fields = (
            'first_name', 'last_name', 'country', 'company_name', 'address', 'postal_code', 'email', 'phone', 'message',
            'is_approved')

manager/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, TemplateView, UpdateView, DeleteView
from furni.models import Checkout
from .forms import OrderForm, EditOrderForm
from django.urls import reverse_lazy


# Create your views here.

# @login_required(login_url='/login/')
# def index(request):
#     return render(request, 'manager.html')


class ManagerCheck(UserPassesTestMixin):
    """
    Manager check test
    """
    def test_func(self):
        return self.request.user.groups.filter(name='managers').exists()


class IndexView(LoginRequiredMixin, ManagerCheck, ListView):
    """
    Index view of manager page
    """
    template_name = 'manager.html'
    model = Checkout
    login_url = '/login/'
    context_object_name = 'reservations'

    def queryset(self):
        return Checkout.objects.filter(is_approved=False).order_by('-created_at')


class IndexOrderView(LoginRequiredMixin, ManagerCheck, UpdateView):
    """
    Working with editor reservation page
    """
    template_name = 'approve.html'
    login_url = '/login/'
    model = Checkout
    form_class = EditOrderForm
    success_url = reverse_lazy('manager:index')

manager/templates/approve.html
{% extends 'index.html' %}

{% block register_content %}
    <div class="container mt-5">
        <h1>Редагувати бронювання</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Зберегти</button>
        </form>
        <a href="{% url 'manager:index' %}" class="btn btn-secondary mt-3">До резервацій</a>
    </div>
{% endblock %}

manager/templates/manager.html
{% extends 'index.html' %}
{% block register_content %}
<div class="container mt-5">
{#        <h1>Список резервацій</h1>#}
        <h1>Order list</h1>
        <div class="list-group mt-4">
            {% for reservation in reservations %}
                <div class="list-group-item">
                    <h5 class="mb-1">{{ reservation.first_name }}</h5>
                    <p class="mb-1">{{ reservation.last_name }}</p>
                    <p class="mb-1">Email: {{ reservation.email}}, Phone: {{ reservation.phone }}</p>
                    <p class="mb-1">Company: {{ reservation.company_name }}</p>
                    <p class="mb-1">Country: {{ reservation.country }}</p>
                    <p class="mb-1">Address: {{ reservation.address }}</p>
                    <p class="mb-1">Postal code: {{ reservation.postal_code }}</p>
                    <a href="{% url 'manager:approve' reservation.id %}" class="btn btn-primary btn-sm float-right">Підтвердити</a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}